### PR TITLE
Rework.

### PR DESCRIPTION
**Pull request by Ky6uk**

### CODE REVIEW

**Comment by kikonejacob** [comment]
Can you explain the advantage of this rework?
I have tried the rework in  recent  IE, Chrome, Firefox and it work fine.
Now It look like the dialog don't load form older version of webkit for android.

**Comment by kikonejacob** [comment]
The main problem with the older version that caused the conflict with bootstrap was the class names. The easiest solution was just to rename the css class name. Can I know what this reword give as advantage compare to the older version?

**Comment by Ky6uk** [comment]
Classname was changed in 0.2.0 on `mn-modal` and will be documented a bit later. Also we didn't test this library on mobile devices.

**Comment by Ky6uk** [comment]
Ahh, tag 0.2.0 wasn't added. Also, @Kikonejacob, what version of android are you using?

**Comment by kikonejacob** [comment]
I have tested it on a samsung galaxy s3 with an android 4.2

**Pull request merged**
